trigger:
- main
 
pool:
  name: 'self-hosted agent' 
 
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
 
- script: |
    echo "Running UFT script..."
    cscript.exe "C:\SFAutomation\FunctionLibrary\LaunchUFT.vbs"
  displayName: 'Run UFT Script'





















