trigger:
- main

pool:
  name: 'self-hosted agent'

steps:
- script: |
    echo "Running pipeline for self hosted agent and program Hello, World!"
  displayName: 'Self-hosted agent Test Hello World Script'
