trigger:
- main  # Trigger the pipeline on commits to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu VM to run the pipeline

steps:
# Step 1: Checkout the code
- task: Checkout@1
  displayName: 'Checkout Code'

# Step 2: Run the Hello World script
- script: |
    python hello.py
  displayName: 'Run Hello World Script'
